import 'package:flutter/material.dart';

abstract final class M3EColorSchemes {
  const M3EColorSchemes._();

  static const ColorScheme dark = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFA78BFA),
    onPrimary: Color(0xFF1E1035),
    primaryContainer: Color(0xFF3B2D54),
    onPrimaryContainer: Color(0xFFE9D8FD),
    secondary: Color(0xFF7DD3FC),
    onSecondary: Color(0xFF082F49),
    secondaryContainer: Color(0xFF164E63),
    onSecondaryContainer: Color(0xFFCFF4FF),
    tertiary: Color(0xFFF9A8D4),
    onTertiary: Color(0xFF4A102F),
    tertiaryContainer: Color(0xFF6B2349),
    onTertiaryContainer: Color(0xFFFFD8EA),
    error: Color(0xFFF87171),
    onError: Color(0xFF450A0A),
    errorContainer: Color(0xFF7F1D1D),
    onErrorContainer: Color(0xFFFFDAD6),
    surface: Color(0xFF0F0F11),
    onSurface: Color(0xFFF1F1F4),
    onSurfaceVariant: Color(0xFFA1A1AA),
    outline: Color(0xFF3F3F46),
    outlineVariant: Color(0xFF27272A),
    surfaceDim: Color(0xFF0C0C0E),
    surfaceBright: Color(0xFF45454D),
    surfaceContainerLowest: Color(0xFF151518),
    surfaceContainerLow: Color(0xFF1D1D21),
    surfaceContainer: Color(0xFF25252A),
    surfaceContainerHigh: Color(0xFF2F2F36),
    surfaceContainerHighest: Color(0xFF3A3A42),
    inverseSurface: Color(0xFFF1F1F4),
    onInverseSurface: Color(0xFF1B1B1F),
    inversePrimary: Color(0xFF6D4DC2),
    scrim: Color(0xFF000000),
    shadow: Color(0xFF000000),
  );

  static final ColorScheme amoled = dark.copyWith(
    surface: Colors.black,
    surfaceDim: Colors.black,
    surfaceContainerLowest: const Color(0xFF0A0A0C),
    surfaceContainerLow: const Color(0xFF121215),
    surfaceContainer: const Color(0xFF1A1A1F),
    surfaceContainerHigh: const Color(0xFF222228),
    surfaceContainerHighest: const Color(0xFF2C2C34),
  );

  static const ColorScheme light = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF6D28D9),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFE9D8FD),
    onPrimaryContainer: Color(0xFF2E1065),
    secondary: Color(0xFF0369A1),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFCFF4FF),
    onSecondaryContainer: Color(0xFF082F49),
    tertiary: Color(0xFFBE185D),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFFFD8EA),
    onTertiaryContainer: Color(0xFF4A102F),
    error: Color(0xFFB91C1C),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFFDAD6),
    onErrorContainer: Color(0xFF450A0A),
    surface: Color(0xFFFBF9FE),
    onSurface: Color(0xFF1B1B1F),
    onSurfaceVariant: Color(0xFF4B4750),
    outline: Color(0xFF79747E),
    outlineVariant: Color(0xFFCAC4D0),
    surfaceDim: Color(0xFFE2E0E6),
    surfaceBright: Color(0xFFFBF9FE),
    surfaceContainerLowest: Color(0xFFFFFFFF),
    surfaceContainerLow: Color(0xFFF5F2F8),
    surfaceContainer: Color(0xFFEFEAF2),
    surfaceContainerHigh: Color(0xFFE9E3EC),
    surfaceContainerHighest: Color(0xFFE2DCE5),
    inverseSurface: Color(0xFF303036),
    onInverseSurface: Color(0xFFF4F0F7),
    inversePrimary: Color(0xFFD0BCFF),
    scrim: Color(0xFF000000),
    shadow: Color(0xFF000000),
  );
}
